django_test/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text

polls/views.py
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.db import connection

from .models import Question

def index(request):
    latest_questions = Question.objects.order_by("-pub_date")[:5]
    return render(request, "polls/index.html", {
        "latest_questions_list": latest_questions
    })

def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    key = "question"
    return render(request, "polls/detail.html", {key: question})

def results(request, question_id):
    response = "Result of question #%s"
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse(f"Voting on #{question_id}")

polls/templates/polls/detail.html
<html>
    <head>
        <title>Poll - Question #{{ question.id }}</title>
    </head>
    <body>
        <h2>Poll - Question #{{ question.id }}</h2>
        <p>{{ question.question_text }}</p>
        <ol>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ol>
    </body>
</html>

polls/templates/polls/index.html
<html>
    <head>
        <title>Polls</title>
    </head>
    <body>
        <h2>Polls</h2>
        {% if latest_questions_list %}
            <ul>
            {% for question in latest_questions_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </body>
</html> 